### PR TITLE
fix: add more emphasis to freelance gigs and remove duplicate text

### PR DESCRIPTION
**Pull request by rija**
Following feedback from Laurie, added more emphasis to freelance gigs.
While doing so, noticed the section on opensource contributions was duplicated.

### CODE REVIEW

**Review by kencho51 — COMMENTED** [review]
Hi @rija,

**praise:** The additional freelance page link in the main page is working.

**suggestion:** Since the freelance link has been moved up, the freelance section at the bottom of this page can be removed as it seems a bit redundant?

**suggestion:** In this page, keywords `contact us` can be found multiple time, but there is no any details about how to do so. Would it be better to have a link, like [contact us](email address) or explicitly embed the method in those section for user convenience?

**Comment by rija** [comment]
> **suggestion:** In this page, keywords `contact us` can be found multiple time, but there is no any details about how to do so. Would it be better to have a link, like [contact us](email address) or explicitly embed the method in those section for user convenience?

Hi @kencho51 

I deliberately left these as non link because:
 * the email address is displayed in the footer already, which link to the contact form.
 * we don't want to influence the method to contact us. If people prefer connecting through social media or other means, it should be an option open to them (there maybe missing icons/links down in the footer but that's outside the scope of this PR I reckon)

**Comment by rija** [comment]
> **suggestion:** Since the freelance link has been moved up, the freelance section at the bottom of this page can be removed as it seems a bit redundant?

Thanks for spotting, now fixed.

**Review by pli888 — APPROVED** [review]
**praise:** Looks fine to me.

**nitpick:** Maybe use the GigaScience Press logo on the `freelance.html` page so it is consistent with the `index.html` page.

**Review by kencho51 — APPROVED** [review]

**Pull request merged**
