### PR TITLE
Add job advert pages

### PR DESCRIPTION
**Pull request by rija**
Implement as static HTML page under ``jobs/tech``:
 
* 2ab3c70 Feat: Add software engineer job advert
* 37f9ce1 Fix: Precise application method and tweak title of senior SE job advert

Can you check that the two job adverts are correct and can be navigated to before I share it with Laurie and others

### CODE REVIEW

**Comment by kencho51** [comment]
Hi @rija,

**praise:** The `software_engineer.html` is working after downloading it to my dev.
**praise:** The layout of the pages matches with the gigadb theme style.
**issue 1**  The `assets/about.png` contains most of the people are not from the Giga team.
**suggestion 1:** Better change it or not showing it?
**issue 2:** The `Home` url (https://gigasciencejournal.com/) is broken. 
**suggestion 2:** Update the `Home` url to https://beta.gigadb.org?
**suggestion 3(non blocking):** Add a dropdown option `jobs` in gigadb website `About` box and link to this job page? It will make these two sites connected.

**Review by kencho51 — COMMENTED** [review]
Hi @rija,

**praise:** The `software_engineer.html` is working after downloading it to my dev.
**praise:** The layout of the pages matches with the gigadb main theme style.
**issue 1**  The `assets/about.png` contains most of the people are not from the Giga team.
**suggestion 1:** Better change it or not showing it?
**issue 2:** The `Home` url (https://gigasciencejournal.com/) is broken. 
**suggestion 2:** Update the `Home` url to https://beta.gigadb.org?
**suggestion 3(non blocking):** Add a dropdown option `jobs` in gigadb website `About` box and link to this job page? It will make these two sites connected.

**Review by pli888 — APPROVED** [review]
The links in the jobs.gigasciencejournal.com home page to the two jobs pages work for me. I would definitely replace the photo on the home page though or just not have a photo for the time being.

**Comment by rija** [comment]
Hi @kencho51 
>**issue 1** The assets/about.png contains most of the people are not from the Giga team.

Understood. It's removed now.

> **issue 2:** The `Home` url (https://gigasciencejournal.com/) is broken.

That url is normally working (clicked it yesterday), it's a redirect to OUP Gigascience journal.
I wonder who to ask to investigate the issue? the OUP site works when accessing it directly (https://academic.oup.com/gigascience). @pli888 we haven't accidentally changed the root DNS record for gigasciencejournal.com, have we?

> **suggestion 2:** Update the `Home` url to https://beta.gigadb.org?

That's not correct I reckon. The jobs  site is related to our organisation, not  just to one of our product (GigaDB), so the "Home" link on that page should go to  the home of our organisation's home page. It's not great that it is a redirect to OUP hosted site, and it's unfortunate that the redirect is currently not working. 
I could link it directly to the OUP web site, but that's dodgy from a visitor's perpective (they don't necessarily know the relationship between Gigascience and OUP, so the change of domain may send the wrong signals)
I'll hide it until the redirect is fixed.

> **suggestion 3(non blocking):** Add a dropdown option `jobs` in gigadb website `About` box and link to this job page? It will make these two sites connected.

That's a good idea. But not just gigadb.org, we need a link to the job site from Gigabyte, from the Gigascience journal, from the blog, and on GigaScience's LinkedIn page
In all cases, it is not going to be done as part of this PR.

**Comment by pli888** [comment]
> we haven't accidentally changed the root DNS record for gigasciencejournal.com, have we?

There is an A record for the root domain and it points to the IP address for the OUP gigascience website. No changes have been made.

**Review by kencho51 — APPROVED** [review]
Hi @rija,

The broken link has been hidden for now, I don't see there are any other blockage now, so I would like to  approve this PR.

**Pull request merged**
